[project]
name = "assets-worker"
version = "0.1.0"
description = "Python assets handling example"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "webtypy>=0.1.7",
]

[dependency-groups]
dev = [
    "workers-py"
]
