name = "hello-python-bindings"
main = "src/entry.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2025-08-14"

kv_namespaces = [
    { binding = "FOO", id = "<YOUR_KV_NAMESPACE_ID>" }
]
