# Generated by Django 5.1.2 on 2025-07-06 13:30

import django.utils.timezone
from django.db import migrations, models


def insert_dummy_blog_post(apps, schema_editor):
    Post = apps.get_model("blog", "Post")

    # Insert the record
    Post.objects.create(
        title="Example Post",
        content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("pub_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RunPython(
            code=insert_dummy_blog_post,
        ),
    ]
